---
- hosts: all
  gather_facts: false
  become: true
  tasks:
  - dnf:
      name: "{{item}}"
      state: present
      disable_gpg_check: true
    with_items:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    when: false
  - dnf:
      name: "{{item}}"
      state: present
    with_items:
      - git
      - vim
      - python3.8
      - go
      - rust
      - python38-devel
      - screen
      - net-tools
      - mosh
    when: true
  - pip:
      name: "{{item}}"
      virtualenv: /home/ec2-user/venv
      virtualenv_command: /usr/bin/python3.8 -m venv
      state: forcereinstall
    with_items:
      - setuptools_rust
      - pip
    when: false
  - pip:
      name: "{{item}}"
      virtualenv: /home/ec2-user/venv
      virtualenv_command: /usr/bin/python3.8 -m venv
    with_items:
      - ansible
    when: false
  - shell:
      cmd: chown -R ec2-user.ec2-user /home/ec2-user/venv
    when: false
  - lineinfile:
      path: /etc/hosts
      line: "{{item}}"
    with_items:
      - 'webserver 44.201.5.56'
    when: true 
...
